site_name: 'Data Engineering Knowledge Base'
site_description: '–õ–∏—á–Ω–∞—è –±–∞–∑–∞ –∑–Ω–∞–Ω–∏–π –∏ –ø—Ä–æ–µ–∫—Ç—ã Data Engineer'
site_author: '–ú–∞–∫—Å–∏–º'
site_url: 'https://dehandbook.ru/'

# üìò –¢–µ–º–∞
theme:
  name: 'material'
  language: 'ru'
  features:
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

# üìÅ –ù–∞–≤–∏–≥–∞—Ü–∏—è
nav:
  - –ì–ª–∞–≤–Ω–∞—è: index.md
  - –û–±–æ –º–Ω–µ: about.md
  - –ü—Ä–æ–µ–∫—Ç—ã: projects.md
  - –ë–∞–∑–∞ –∑–Ω–∞–Ω–∏–π:
      - Python:
          - –û—Å–Ω–æ–≤—ã: knowleddge/python/basics.md
          - Pandas: knowleddge/python/pandas.md
          - –°–æ–≤–µ—Ç—ã: knowleddge/python/tips.md
      - SQL:
          - –û—Å–Ω–æ–≤—ã: notes/sql.md
      - Airflow:
          - –ó–∞–º–µ—Ç–∫–∏: notes/airflow.md
  - –ö—É—Ä—Å—ã –∏ –æ–±—É—á–µ–Ω–∏–µ:
      - Python –∫—É—Ä—Å: courses/python_course.md
      - Stepik ML: courses/stepik.md
      - LeetCode –∑–∞–º–µ—Ç–∫–∏: courses/leetcode_notes.md
  - –ó–∞–º–µ—Ç–∫–∏:
      - Python: notes/python.md
      - Airflow: notes/airflow.md
      - SQL: notes/sql.md
  - –†–∞–∑–≤–∏—Ç–∏–µ: progress.md
  - –ú–µ–¥–∏–∞: contacts.md
  - –ü–æ–ª–µ–∑–Ω—ã–µ —Ä–µ—Å—É—Ä—Å—ã: useful_resources.md

# üß© –†–∞—Å—à–∏—Ä–µ–Ω–∏—è Markdown
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.emoji

# üîç –ü–ª–∞–≥–∏–Ω—ã
plugins:
  - search
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
  - awesome-pages

# üìÑ –î–æ–ø–æ–ª–Ω–∏—Ç–µ–ª—å–Ω–æ
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TheDataWanderer
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/nefatov/
    - icon: fontawesome/brands/telegram
      link: https://t.me/@maksim_flow
  generator: false